name: Deploy GCP Streaming Infra

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      destroy:
        description: "Destroy resources?"
        required: true
        default: "false"
        type: choice
        options: ["false", "true"]

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref || github.ref_name, 'prod/') || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ fromJson(secrets.GCP_CREDENTIALS_JSON).project_id }}
          install_components: 'beta'

      - run: |
          echo "TF_VAR_project_id=${{ fromJson(secrets.GCP_CREDENTIALS_JSON).project_id }}" >> $GITHUB_ENV
          echo "TF_VAR_region=us-central1" >> $GITHUB_ENV
          echo "TF_VAR_env=prod" >> $GITHUB_ENV

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Create Dataflow temp bucket if not exists
      - run: |
          PROJECT_ID=${{ fromJson(secrets.GCP_CREDENTIALS_JSON).project_id }}
          BUCKET="cars-sales-${PROJECT_ID}-prod-dataflow-temp"
          gsutil ls -b gs://${BUCKET} >/dev/null 2>&1 || gsutil mb -l us-central1 gs://${BUCKET}

      # Upload only simplified main.py
      - if: ${{ github.event.inputs.destroy != 'true' }}
        run: |
          PROJECT_ID=${{ fromJson(secrets.GCP_CREDENTIALS_JSON).project_id }}
          BUCKET="cars-sales-${PROJECT_ID}-prod-dataflow-temp"
          gsutil -m cp ./dataflow/main.py gs://${BUCKET}/template/main.py

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          pip install "apache-beam[gcp]==2.54.0"

      # Build Dataflow template (no streaming flag here)
      - if: ${{ github.event.inputs.destroy != 'true' }}
        run: |
          PROJECT_ID=${{ fromJson(secrets.GCP_CREDENTIALS_JSON).project_id }}
          BUCKET="cars-sales-${PROJECT_ID}-prod-dataflow-temp"

          python3 dataflow/main.py \
            --runner DataflowRunner \
            --project ${PROJECT_ID} \
            --region us-central1 \
            --temp_location gs://${BUCKET}/temp \
            --template_location gs://${BUCKET}/template/main-template

      # Terraform apply or destroy
      - working-directory: ./infra
        run: terraform init

      - working-directory: ./infra
        run: |
          if [ "${{ github.event.inputs.destroy }}" == "true" ]; then
            terraform destroy -auto-approve
          else
            terraform apply -auto-approve
          fi