name: Deploy GCP Streaming Infra

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

  workflow_dispatch:
    inputs:
      destroy:
        description: "Deseja destruir os recursos?"
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

jobs:
  terraform:
    name: Terraform Deploy or Destroy - Capabilities
    runs-on: ubuntu-latest

    if: startsWith(github.head_ref || github.ref_name, 'prod/') || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v3

      - name: Configurar credenciais GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Configurar projeto GCP
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ fromJson(secrets.GCP_CREDENTIALS_JSON).project_id }}
          install_components: 'beta'

      - name: Exportar vari√°veis Terraform
        run: |
          echo "TF_VAR_project_id=${{ fromJson(secrets.GCP_CREDENTIALS_JSON).project_id }}" >> $GITHUB_ENV
          echo "TF_VAR_region=us-central1" >> $GITHUB_ENV
          echo "TF_VAR_env=prod" >> $GITHUB_ENV
          echo "TF_VAR_account_id=${{ fromJson(secrets.GCP_CREDENTIALS_JSON).project_id }}" >> $GITHUB_ENV

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Criar o bucket de template se n√£o existir
      - name: Criar bucket de template se n√£o existir
        run: |
          PROJECT_ID=${{ fromJson(secrets.GCP_CREDENTIALS_JSON).project_id }}
          REGION=us-central1
          ENV=prod
          BUCKET="cars-sales-${PROJECT_ID}-${ENV}-dataflow-temp"
          
          echo "Verificando se o bucket ${BUCKET} existe..."
          if ! gsutil ls -b gs://${BUCKET} >/dev/null 2>&1; then
            echo "Bucket n√£o encontrado. Criando o bucket ${BUCKET}..."
            gsutil mb -l ${REGION} gs://${BUCKET}
          else
            echo "Bucket ${BUCKET} j√° existe."
          fi

      # Upload dos scripts Python para o bucket template do Dataflow
      - name: Upload dos scripts Dataflow (.py) para o bucket template
        if: ${{ github.event.inputs.destroy != 'true' }}
        run: |
          PROJECT_ID=${{ fromJson(secrets.GCP_CREDENTIALS_JSON).project_id }}
          ENV=prod
          BUCKET="cars-sales-${PROJECT_ID}-${ENV}-dataflow-temp"

          echo "üì¶ Enviando scripts Python para gs://${BUCKET}/template/"
          gsutil -m cp ./dataflow/main.py gs://${BUCKET}/template/
          gsutil -m cp -r ./dataflow/utils gs://${BUCKET}/template/utils

      # Gerar o template do Dataflow
      - name: Gerar template do Dataflow
        if: ${{ github.event.inputs.destroy != 'true' }}
        run: |
          PROJECT_ID=${{ fromJson(secrets.GCP_CREDENTIALS_JSON).project_id }}
          ENV=prod
          REGION=us-central1
          BUCKET="cars-sales-${PROJECT_ID}-${ENV}-dataflow-temp"

          echo "üèóÔ∏è Gerando template do Dataflow..."
          python3 dataflow/main.py \
            --runner DataflowRunner \
            --project ${PROJECT_ID} \
            --region ${REGION} \
            --temp_location gs://${BUCKET}/temp \
            --template_location gs://${BUCKET}/template/main-template

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Apply ou Destroy
        working-directory: ./infra
        run: |
          if [ "${{ github.event.inputs.destroy }}" == "true" ]; then
            echo "‚ö†Ô∏è Destruindo infraestrutura GCP..."
            terraform destroy -auto-approve
          else
            echo "üöÄ Aplicando infraestrutura GCP..."
            terraform apply -auto-approve
          fi
